package trainer.engine.content

object Scenarios {

    private fun opts(vararg pairs: Pair<String, String>) = pairs.map { ActionOption(it.first, it.second) }

    val all: List<Scenario> = listOf(
        // --- position ---
        Scenario(
            id = "position-1",
            lessonId = "position",
            prompt = "You're under the gun, first to act, at a full table. No one has entered the pot.",
            heroCards = "J♦ 9♦",
            board = null,
            potBeforeAction = 3,
            betFacing = null,
            options = opts("raise" to "Open-raise", "fold" to "Fold"),
            correctOptionId = "fold",
            explanation = "Suited one-gappers are fine from late position but too speculative to open from the first seat, where the rest of the table still gets to act behind you.",
        ),
        Scenario(
            id = "position-2",
            lessonId = "position",
            prompt = "Action folds to you on the button. No one has entered the pot.",
            heroCards = "J♦ 9♦",
            board = null,
            potBeforeAction = 3,
            betFacing = null,
            options = opts("raise" to "Open-raise", "fold" to "Fold"),
            correctOptionId = "raise",
            explanation = "Same hand, different seat. On the button you'll be in position for the rest of the hand against anyone who calls, so the range you open with gets much wider.",
        ),
        Scenario(
            id = "position-3",
            lessonId = "position",
            prompt = "You're in the big blind. A tight player raises from under the gun and everyone else folds to you.",
            heroCards = "8♣ 7♣",
            board = null,
            potBeforeAction = 4,
            betFacing = 3,
            options = opts("call" to "Call", "fold" to "Fold", "raise" to "Re-raise"),
            correctOptionId = "fold",
            explanation = "You're getting a price, but you'll be out of position for the rest of the hand against a tight range. Speculative hands lose value when you can't control the pot after the flop.",
        ),

        // --- ranges ---
        Scenario(
            id = "ranges-1",
            lessonId = "ranges",
            prompt = "An opponent who has only three-bet twice in 100 hands suddenly three-bets you. What's the best read on their range?",
            heroCards = "—",
            board = null,
            potBeforeAction = 6,
            betFacing = null,
            options = opts(
                "wide" to "Likely a wide, speculative range",
                "narrow" to "Likely a narrow, strong range",
            ),
            correctOptionId = "narrow",
            explanation = "A player who three-bets rarely is telling you their range is tight when they finally do it. Frequency is information — read the player's history, not just the action in isolation.",
        ),
        Scenario(
            id = "ranges-2",
            lessonId = "ranges",
            prompt = "On a 2♠ 7♦ 9♣ flop, who generally has the range advantage: the preflop raiser from the button, or the big blind who just called?",
            heroCards = "—",
            board = "2♠ 7♦ 9♣",
            potBeforeAction = 8,
            betFacing = null,
            options = opts("raiser" to "The button raiser", "caller" to "The big blind"),
            correctOptionId = "raiser",
            explanation = "A button open-raising range is built from strong high cards and pairs, which connects with or beats a disconnected low flop far more often than a wide big-blind calling range does.",
        ),
        Scenario(
            id = "ranges-3",
            lessonId = "ranges",
            prompt = "Your opponent checks back the flop and river in a heads-up pot with no action anywhere. What can you rule out of their range?",
            heroCards = "—",
            board = null,
            potBeforeAction = 10,
            betFacing = null,
            options = opts("nutted" to "Their very best possible hands", "weak" to "Weak, unmade hands"),
            correctOptionId = "nutted",
            explanation = "A player holding the nuts in a heads-up pot almost always finds a way to get money in. Two checks in a row sharply narrows their range away from the top of it.",
        ),

        // --- cbet ---
        Scenario(
            id = "cbet-1",
            lessonId = "cbet",
            prompt = "You raised preflop from the cutoff and got one caller from the big blind. Flop comes K♠ 7♦ 2♣ — dry and disconnected.",
            heroCards = "A♥ Q♥",
            board = "K♠ 7♦ 2♣",
            potBeforeAction = 7,
            betFacing = null,
            options = opts("bet" to "Bet small", "check" to "Check back"),
            correctOptionId = "bet",
            explanation = "Your range (built from cutoff opens) hits this king-high dry board much harder than a big-blind calling range does. A small continuation bet applies pressure cheaply and often wins immediately.",
        ),
        Scenario(
            id = "cbet-2",
            lessonId = "cbet",
            prompt = "Same raise, but the flop comes J♥ T♥ 9♠ — very wet, with straights and flushes both live.",
            heroCards = "A♣ 4♣",
            board = "J♥ T♥ 9♠",
            potBeforeAction = 7,
            betFacing = null,
            options = opts("betbig" to "Bet big", "betsmall" to "Bet small", "check" to "Check back"),
            correctOptionId = "check",
            explanation = "Wet boards like this hit a wide calling range hard, so your range edge shrinks and your hand has no pair or draw. Checking back controls the pot size instead of bloating it with little equity.",
        ),
        Scenario(
            id = "cbet-3",
            lessonId = "cbet",
            prompt = "You continuation-bet a dry flop and get called. The turn pairs the board (K♠ 7♦ 2♣ 7♥), which rarely helps a calling range.",
            heroCards = "A♥ Q♥",
            board = "K♠ 7♦ 2♣ 7♥",
            potBeforeAction = 11,
            betFacing = null,
            options = opts("bet" to "Bet again", "check" to "Check back"),
            correctOptionId = "bet",
            explanation = "A second barrel keeps pressure on a range that mostly can't have improved. Firing again on a card that helps your range more than theirs is a classic spot to keep betting.",
        ),

        // --- checkraise ---
        Scenario(
            id = "checkraise-1",
            lessonId = "checkraise",
            prompt = "You're out of position with a set on a coordinated flop. Your opponent bets.",
            heroCards = "9♦ 9♣",
            board = "9♠ T♥ J♦",
            potBeforeAction = 10,
            betFacing = 6,
            options = opts("raise" to "Check-raise", "call" to "Call only"),
            correctOptionId = "raise",
            explanation = "A wet board with a strong, well-disguised hand is exactly when to raise for value — your set is well ahead of most of the hands that would call a bet or a raise here, and the board won't stay this favorable forever.",
        ),
        Scenario(
            id = "checkraise-2",
            lessonId = "checkraise",
            prompt = "You check a flop that favors your checking range, holding a backdoor-only hand, and your opponent bets small.",
            heroCards = "A♦ 5♦",
            board = "K♦ 8♥ 3♦",
            potBeforeAction = 8,
            betFacing = 4,
            options = opts("raise" to "Check-raise as a bluff", "fold" to "Fold"),
            correctOptionId = "raise",
            explanation = "Your hand has a backdoor flush draw and blocks some of the ace-high hands your opponent might continue with — a reasonable, low-frequency bluff-raise candidate rather than a hand you need to fold outright.",
        ),
        Scenario(
            id = "checkraise-3",
            lessonId = "checkraise",
            prompt = "You check-raise every single time you flop two pair or better, and never with anything else. A sharp opponent has caught on.",
            heroCards = "—",
            board = null,
            potBeforeAction = 10,
            betFacing = null,
            options = opts("good" to "This is a sound long-term strategy", "bad" to "This is exploitable"),
            correctOptionId = "bad",
            explanation = "A check-raise range with no bluffs in it is simple to play against: opponents just fold everything but their own strong hands and never pay you off. Mixing in some bluffs is what keeps the raise profitable.",
        ),

        // --- threebet ---
        Scenario(
            id = "threebet-1",
            lessonId = "threebet",
            prompt = "A loose player opens from the cutoff. You're on the button.",
            heroCards = "A♠ Q♠",
            board = null,
            potBeforeAction = 3,
            betFacing = 2,
            options = opts("threebet" to "Three-bet", "call" to "Call", "fold" to "Fold"),
            correctOptionId = "threebet",
            explanation = "Ace-queen suited is comfortably ahead of a loose opening range and plays better as the aggressor than as a flat-caller who'll often face tough decisions out of position on later streets — here you'd still be in position, but building the pot with a hand this strong is still preferred against a wide range.",
        ),
        Scenario(
            id = "threebet-2",
            lessonId = "threebet",
            prompt = "You're in the small blind. A tight, straightforward player opens from under the gun.",
            heroCards = "7♣ 7♦",
            board = null,
            potBeforeAction = 3,
            betFacing = 2,
            options = opts("threebet" to "Three-bet", "call" to "Call", "fold" to "Fold"),
            correctOptionId = "call",
            explanation = "Against a tight range, small pairs flip from a three-bet candidate into more of a set-mining call: you'll often be dominated if a four-bet comes back, but you can call cheaply to try to hit a set and win a big pot instead.",
        ),
        Scenario(
            id = "threebet-3",
            lessonId = "threebet",
            prompt = "You've three-bet the last four times you've had a chance to in this session, always folding when four-bet. An observant opponent four-bets you again.",
            heroCards = "K♦ J♦",
            board = null,
            potBeforeAction = 20,
            betFacing = 14,
            options = opts("call" to "Call the four-bet", "fold" to "Fold", "jam" to "Move all-in"),
            correctOptionId = "fold",
            explanation = "You've shown a pattern (three-bet often, fold to four-bets), so a sharp opponent can four-bet you light knowing you'll fold. The lesson here is about your own pattern going forward: once spotted, you need to defend some three-bets to stay unpredictable — but with this exact hand in this exact spot, folding is still fine.",
        ),

        // --- betsizing ---
        Scenario(
            id = "betsizing-1",
            lessonId = "betsizing",
            prompt = "You flop a flush draw and want to bet it as a semi-bluff on a wet board where opponents have a lot of weak pairs that might call. What's the sizing goal?",
            heroCards = "6♥ 7♥",
            board = "8♥ 9♥ 2♣",
            potBeforeAction = 10,
            betFacing = null,
            options = opts("big" to "Bet big to charge draws and fold out weak pairs", "small" to "Bet small to look passive"),
            correctOptionId = "big",
            explanation = "On a board this wet, a bigger bet makes it expensive for other draws to continue and can fold out some one-pair hands outright, while you still have plenty of outs if you're called.",
        ),
        Scenario(
            id = "betsizing-2",
            lessonId = "betsizing",
            prompt = "You have the nuts on a dry board against an opponent who only calls down with medium-strength hands and folds to big bets.",
            heroCards = "A♣ A♦",
            board = "A♠ 7♦ 2♣",
            potBeforeAction = 10,
            betFacing = null,
            options = opts("small" to "Bet small to keep them in", "big" to "Bet big for maximum value"),
            correctOptionId = "small",
            explanation = "Value betting is about getting called by worse, not about betting the biggest number possible. Against someone who folds to big bets, a smaller bet keeps their calling range in and wins more chips overall.",
        ),
        Scenario(
            id = "betsizing-3",
            lessonId = "betsizing",
            prompt = "An opponent who has bet a consistent one-third pot all session suddenly bets the full pot in one hand. What should you read into this?",
            heroCards = "—",
            board = null,
            potBeforeAction = 12,
            betFacing = 12,
            options = opts("tell" to "The sizing change is a meaningful tell", "ignore" to "Sizing doesn't carry information"),
            correctOptionId = "tell",
            explanation = "A sudden break from an established pattern — in timing or in sizing — is one of the most reliable signals at the table, precisely because most players size bets unconsciously based on how they feel about their hand.",
        ),

        // --- potodds ---
        Scenario(
            id = "potodds-1",
            lessonId = "potodds",
            prompt = "The pot is 60 and your opponent bets 30. You hold a flush draw (9 outs) with two cards to come. Is calling justified on the math alone?",
            heroCards = "K♥ Q♥",
            board = "9♥ 4♥ 2♣",
            potBeforeAction = 60,
            betFacing = 30,
            options = opts("call" to "Call", "fold" to "Fold"),
            correctOptionId = "call",
            explanation = "Required equity = 30 / (60 + 30 + 30) = 25%. Nine outs with two cards to come is roughly 9×4 = 36% equity by the quick-count shortcut. 36% clears the 25% bar, so this is a profitable call on pot odds alone.",
        ),
        Scenario(
            id = "potodds-2",
            lessonId = "potodds",
            prompt = "The pot is 20 and your opponent bets 20 (pot-sized). You have a gutshot straight draw only (4 outs) with one card to come.",
            heroCards = "J♣ T♣",
            board = "9♠ 4♦ 2♥ Q♣",
            potBeforeAction = 20,
            betFacing = 20,
            options = opts("call" to "Call", "fold" to "Fold"),
            correctOptionId = "fold",
            explanation = "Required equity = 20 / (20+20+20) = 33%. Four outs with one card to come is about 4×2 = 8% equity. That's far short of 33%, so folding is correct unless you have strong implied odds or another reason to continue.",
        ),
        Scenario(
            id = "potodds-3",
            lessonId = "potodds",
            prompt = "The pot is 50 before your bet. You want to bluff and are deciding a size. At a bet of 25, what fold frequency do you need from your opponent to break even?",
            heroCards = "—",
            board = null,
            potBeforeAction = 50,
            betFacing = null,
            options = opts("33" to "About 33%", "50" to "About 50%", "67" to "About 67%"),
            correctOptionId = "33",
            explanation = "Break-even bluff frequency = bet / (pot + bet) = 25 / (50 + 25) ≈ 33%. A half-pot bluff only needs to work about a third of the time to show a profit, which is why smaller bluffs are easier to make profitable than large ones.",
        ),

        // --- bluffing ---
        Scenario(
            id = "bluffing-1",
            lessonId = "bluffing",
            prompt = "On a river where the only missed draw was a flush, which of your bluff candidates is the better choice?",
            heroCards = "—",
            board = null,
            potBeforeAction = 40,
            betFacing = null,
            options = opts(
                "blocker" to "A hand holding one of the flush suit's cards",
                "offsuit" to "A fully unrelated offsuit hand",
            ),
            correctOptionId = "blocker",
            explanation = "Holding a card of the flush suit reduces the number of missed-flush combinations your opponent could be sitting behind and, more importantly, removes one of the hands they might have made it with — a textbook blocker bluff.",
        ),
        Scenario(
            id = "bluffing-2",
            lessonId = "bluffing",
            prompt = "You've bet the flop, turn, and river with every single strong hand you've shown down this session, and checked everything else. Is your river bet believable as a bluff?",
            heroCards = "—",
            board = null,
            potBeforeAction = 30,
            betFacing = null,
            options = opts("yes" to "Yes, the line is consistent", "no" to "No, observant opponents will catch on"),
            correctOptionId = "no",
            explanation = "If betting always means strong and checking always means weak, attentive opponents stop needing to guess. Credible bluffs take the same line your value hands would take — the line should be an inseparable disguise, not a tell.",
        ),
        Scenario(
            id = "bluffing-3",
            lessonId = "bluffing",
            prompt = "You hold a hand that beats nothing an aggressive opponent would check back with, but loses to everything they'd bet. On the river they check to you.",
            heroCards = "4♣ 3♣",
            board = "K♠ 9♦ 6♥ 2♣ 8♠",
            potBeforeAction = 30,
            betFacing = null,
            options = opts("bet" to "Bet as a bluff", "check" to "Check and give up"),
            correctOptionId = "bet",
            explanation = "This is a hand that can only win by betting — it has no showdown value, so checking guarantees a loss. A hand that beats only bluffs and loses to everything else is precisely the kind of hand a mixed, balanced bluffing range needs.",
        ),
    )

    fun forLesson(lessonId: String): List<Scenario> = all.filter { it.lessonId == lessonId }
}
